language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r myProject *
  - mkdir -p deploy
  - mv myProject.zip deploy/myProject.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo setting 설정 값

    secret_access_key: $AWS_SECRET_KEY # Travis repo 설정 값

    bucket: gmx0807-springboot2-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일접근을 private로
    local_dir: deploy # before_deploy에 생성한 디렉토리
    wait-until-deployed: true

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - gmx0807@gmail.com